#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null 2>&1 && pwd)
COMPONENT_DIR="$ROOT_DIR/cli/dumpfile"
SETUP_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dumpfile"
SETUP_STATE="$SETUP_DIR/setup.env"
LOCAL_CONFIG="$SETUP_DIR/config.env"
mkdir -p "$SETUP_DIR"
touch "$SETUP_STATE"
chmod 600 "$SETUP_STATE"
ENV_FILE="$SETUP_STATE"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf '  %s✗ %s is required%s\n' "$RED" "$1" "$RESET" >&2
    exit 1
  fi
}

valid_hex_id() {
  [[ "$1" =~ ^[a-f0-9]{32}$ ]]
}

banner "Dumpfile setup"

stage "Cloudflare account and zone"
say "This checks the local toolchain, authenticates Wrangler, and records public account identifiers."
for command in bun curl openssl xxd; do require_command "$command"; done
if ! bunx wrangler whoami; then
  step "Complete the Cloudflare login opened by Wrangler."
  bunx wrangler login
  bunx wrangler whoami
fi
step "Copy the 32-character account ID shown by 'wrangler whoami'."
ask CLOUDFLARE_ACCOUNT_ID "Cloudflare account ID:"
valid_hex_id "$CLOUDFLARE_ACCOUNT_ID" || { warn "expected a 32-character hexadecimal account ID"; exit 1; }
export CLOUDFLARE_ACCOUNT_ID
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/drsh4dow.dev"
step "On the zone Overview page, find API in the right sidebar and copy Zone ID."
ask CLOUDFLARE_ZONE_ID "drsh4dow.dev zone ID:"
valid_hex_id "$CLOUDFLARE_ZONE_ID" || { warn "expected a 32-character hexadecimal zone ID"; exit 1; }
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_ZONE_ID "$CLOUDFLARE_ZONE_ID"
chmod 600 "$SETUP_STATE"

stage "R2 bucket"
say "The bucket is adopted when it already exists and created otherwise."
if bunx wrangler r2 bucket list | grep -Fq 'dumpfile-prod'; then
  note "dumpfile-prod already exists"
else
  bunx wrangler r2 bucket create dumpfile-prod
fi
say "Uploads become eligible for deletion at 30 days of object age, including existing uploads."
bunx wrangler r2 bucket lifecycle list dumpfile-prod
if ! bunx wrangler auth token --json | bun "$COMPONENT_DIR/src/retention.ts" check "$CLOUDFLARE_ACCOUNT_ID"; then
  warn "Retention is not verified. Applying it can expire every existing upload older than 30 days."
  say "Deletion is asynchronous and cannot be undone. Review other lifecycle rules above."
  say "To approve ALL existing and future uploads, type exactly: expire dumpfile-prod uploads"
  RETENTION_APPROVAL=""
  read -r RETENTION_APPROVAL || true
  if [[ "$RETENTION_APPROVAL" == "expire dumpfile-prod uploads" ]]; then
    bunx wrangler auth token --json | bun "$COMPONENT_DIR/src/retention.ts" apply "$CLOUDFLARE_ACCOUNT_ID" --expire-existing-uploads
  else
    SKIPPED+=("30-day retention was not applied or verified; see cli/dumpfile/README.md")
    warn "Continuing without changing retention."
  fi
fi

stage "Bucket-scoped R2 credentials"
say "Create one credential that can write objects only in dumpfile-prod. It stays in this shell until Worker deployment."
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/r2/api-tokens"
step "Choose Create API token, then Object Read & Write."
step "Apply it only to the dumpfile-prod bucket and create the token."
step "Copy the Access Key ID and Secret Access Key. Cloudflare shows the secret once."
ask_secret R2_ACCESS_KEY_ID "R2 Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "R2 Secret Access Key:"
[[ -n "$R2_ACCESS_KEY_ID" && -n "$R2_SECRET_ACCESS_KEY" ]] || { warn "both R2 credentials are required"; exit 1; }

stage "pi-local upload token"
say "The client keeps the bearer token. The Worker receives only its SHA-256 digest."
DUMPFILE_TOKEN=""
if [[ -f "$LOCAL_CONFIG" ]]; then
  DUMPFILE_TOKEN=$(grep -E '^DUMPFILE_TOKEN=' "$LOCAL_CONFIG" | tail -n1 | cut -d= -f2- || true)
fi
if [[ -n "$DUMPFILE_TOKEN" ]]; then
  if confirm "Rotate the existing pi-local token?"; then
    DUMPFILE_TOKEN=$(openssl rand -hex 32)
  else
    note "keeping the current pi-local token"
  fi
else
  DUMPFILE_TOKEN=$(openssl rand -hex 32)
fi
DUMPFILE_TOKEN_SHA256=$(printf '%s' "$DUMPFILE_TOKEN" | openssl dgst -sha256 -binary | xxd -p -c 256)

stage "Signer Worker"
say "Wrangler bundles the signer, installs all four secrets in one deployment, and claims upload.drsh4dow.dev."
SECRETS_FILE=$(mktemp)
chmod 600 "$SECRETS_FILE"
trap 'rm -f "$SECRETS_FILE"' EXIT
{
  printf 'CLOUDFLARE_ACCOUNT_ID=%s\n' "$CLOUDFLARE_ACCOUNT_ID"
  printf 'R2_ACCESS_KEY_ID=%s\n' "$R2_ACCESS_KEY_ID"
  printf 'R2_SECRET_ACCESS_KEY=%s\n' "$R2_SECRET_ACCESS_KEY"
  printf 'DUMPFILE_TOKEN_SHA256=%s\n' "$DUMPFILE_TOKEN_SHA256"
} > "$SECRETS_FILE"
(
  cd "$ROOT_DIR"
  bunx wrangler deploy --config "$COMPONENT_DIR/wrangler.jsonc" --secrets-file "$SECRETS_FILE"
)
rm -f "$SECRETS_FILE"
trap - EXIT
unset R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY DUMPFILE_TOKEN_SHA256
OLD_ENV_FILE="$ENV_FILE"
ENV_FILE="$LOCAL_CONFIG"
write_env DUMPFILE_API_URL "https://upload.drsh4dow.dev"
write_env DUMPFILE_R2_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env DUMPFILE_TOKEN "$DUMPFILE_TOKEN"
chmod 600 "$LOCAL_CONFIG"
ENV_FILE="$OLD_ENV_FILE"

stage "Public R2 domain"
say "This attaches files.drsh4dow.dev directly to R2 and removes the throttled r2.dev path."
if bunx wrangler r2 bucket domain list dumpfile-prod | grep -Fq 'files.drsh4dow.dev'; then
  note "files.drsh4dow.dev is already attached"
else
  bunx wrangler r2 bucket domain add dumpfile-prod \
    --domain files.drsh4dow.dev \
    --zone-id "$CLOUDFLARE_ZONE_ID" \
    --min-tls 1.2 \
    --force
fi
bunx wrangler r2 bucket dev-url disable dumpfile-prod --force
bunx wrangler r2 bucket dev-url get dumpfile-prod

stage "Public response protection"
say "Set one response header rule so browsers never guess an executable type."
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/drsh4dow.dev/rules"
step "Choose Create rule, then Response Header Transform Rule. The rule must appear under Response Header Transform Rules, not Request Header Transform Rules."
step "Name it 'Dumpfile nosniff' and match Hostname equals files.drsh4dow.dev."
step "Set static response header X-Content-Type-Options to nosniff, then deploy the rule."
confirm "Is the Dumpfile nosniff rule deployed?" || { warn "the response rule is required before verification"; exit 1; }
PROBE_HEADERS=$(mktemp)
if ! curl -sSI --max-time 15 "https://files.drsh4dow.dev/__dumpfile_header_probe_$(date +%s)" > "$PROBE_HEADERS"; then
  rm -f "$PROBE_HEADERS"
  warn "files.drsh4dow.dev did not answer the live header probe"
  exit 1
fi
if ! grep -Eiq '^x-content-type-options: nosniff' "$PROBE_HEADERS"; then
  rm -f "$PROBE_HEADERS"
  warn "the live response is missing X-Content-Type-Options: nosniff"
  step "Edit the rule in the drsh4dow.dev zone. It must be listed under Response Header Transform Rules, not Request Header Transform Rules."
  step "Match Hostname equals files.drsh4dow.dev, set static response header X-Content-Type-Options to nosniff, and deploy."
  exit 1
fi
rm -f "$PROBE_HEADERS"
note "the live public response includes nosniff"

stage "Budget alert"
say "The alert reports account-wide usage spend. It does not stop traffic."
open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/billing/billable-usage"
step "Choose Create budget alert."
step "Name it 'dumpfile budget', set the threshold to \$10, and add your email."
step "Save the alert."
confirm "Is the \$10 budget alert active?" || { warn "the budget alert is a launch requirement"; exit 1; }

stage "Local dumpfile command"
say "The command is a symlink to this checkout, so repository updates replace it in place."
mkdir -p "$HOME/.local/bin"
ln -sfn "$COMPONENT_DIR/bin/dumpfile" "$HOME/.local/bin/dumpfile"
chmod +x "$COMPONENT_DIR/bin/dumpfile"
note "installed $HOME/.local/bin/dumpfile"
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  warn "$HOME/.local/bin is not on PATH; add it before starting a new agent"
fi

stage "End-to-end proof"
say "A one-pixel PNG proves authorization, direct upload, public bytes, and response metadata."
FIXTURE_BASE=$(mktemp)
FIXTURE="$FIXTURE_BASE.png"
mv "$FIXTURE_BASE" "$FIXTURE"
FETCHED=$(mktemp)
HEADERS=$(mktemp)
trap 'rm -f "$FIXTURE" "$FETCHED" "$HEADERS"' EXIT
printf '%s' '89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d4944415408d763f8cfc0f01f00050001ff89993d1d0000000049454e44ae426082' | xxd -r -p > "$FIXTURE"
PUBLIC_URL=$(_existing DUMPFILE_VERIFIED_URL || true)
if [[ "$PUBLIC_URL" != https://files.drsh4dow.dev/* ]] || ! curl -fsSI "$PUBLIC_URL" >/dev/null; then
  PUBLIC_URL=$("$HOME/.local/bin/dumpfile" upload "$FIXTURE")
  write_env DUMPFILE_VERIFIED_URL "$PUBLIC_URL"
else
  note "reusing the verified fixture from the previous setup run"
fi
curl -fsSI "$PUBLIC_URL" > "$HEADERS"
grep -Eiq '^content-type: image/png' "$HEADERS" || { warn "public Content-Type is wrong"; exit 1; }
grep -Eiq '^cache-control: public, max-age=31536000, immutable' "$HEADERS" || { warn "public Cache-Control is wrong"; exit 1; }
grep -Eiq '^content-disposition: inline' "$HEADERS" || { warn "public Content-Disposition is wrong"; exit 1; }
grep -Eiq '^x-content-type-options: nosniff' "$HEADERS" || { warn "public nosniff header is missing"; exit 1; }
curl -fsS "$PUBLIC_URL" > "$FETCHED"
cmp "$FIXTURE" "$FETCHED" || { warn "public bytes differ from the uploaded fixture"; exit 1; }
note "verified $PUBLIC_URL"
rm -f "$FIXTURE" "$FETCHED" "$HEADERS"
trap - EXIT

finish
